/*
  Created by GuntherCloudSolutions
  Last updated: 2026-06-28
  Generates ../../seed-data.js from the pinned "Job Search Dashboard" artifact data.
  Pipeline cards already match app.html's schema; STAR stories match; interview prep
  maps talking_points->points and watch_for->watch.
*/
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ADDITIONS = [
  { id:'amazon-recruiter-1', company:'Amazon (AWS)', role:'Recruiter Screen – Solutions Architect', loc:'remote', salary:'', clearance:'no', stage:2, notes:'Recruiter Call Jun 22, 2pm ET. +1 (202) 531-9876. Contact: shaunnav@amazon.com', added:'2026-06-10', stageDate:'2026-06-10' },
  { id:'amazon-sa-1', company:'Amazon (AWS)', role:'Senior Solutions Architect – WWPS Partners SA', loc:'remote', salary:'', clearance:'no', stage:3, notes:'Phone Interview Jun 24, 10:30am. Interviewer: Andy Banks. Zoom 92792832434 / PW 13048620. Contact: shaunnav@amazon.com', added:'2026-06-17', stageDate:'2026-06-17' },
  { id:'fourpoints-1', company:'Four Points Technology', role:'Sr. Solutions Architect', loc:'hybrid', salary:'', clearance:'no', stage:3, notes:'Virtual Interview Jun 22, 10am ET. Teams. Panel: Erik Korondy, Joel Lipkin, Dana Bean, Denise Harrison (CIO), Lori Constantino (lconstantino@4points.com).', added:'2026-06-17', stageDate:'2026-06-19' },
  { id:'missionbridge-1', company:'Mission Bridge Partners', role:'Senior Solutions Architect (HHS)', loc:'remote', salary:'', clearance:'no', stage:2, notes:'Opportunity Discussion Jun 18, 2pm. Teams. Evan McIntosh (evan@missionbridgepartners.com).', added:'2026-06-16', stageDate:'2026-06-16' },
  { id:'covalent-1', company:'Covalent Solutions', role:'Principal Enterprise Infrastructure Architect', loc:'remote', salary:'', clearance:'no', stage:2, notes:'Video call Jun 18, 9am. Google Meet. Thi Pham (thi.pham@covalentsolutions.com).', added:'2026-06-16', stageDate:'2026-06-16' },
  { id:'hamptonnorth-1', company:'Hampton North', role:'Technical Lead, Platform & Cyber Resilience', loc:'remote', salary:'', clearance:'no', stage:2, notes:'Recruiter call Jun 23, 1:20–1:40pm ET. Ruby Murphy (ruby.murphy@hamptonnorth.com), calling from (323) 989-1650.', added:'2026-06-18', stageDate:'2026-06-19' },
  { id:'onstak-1', company:'Onstak Inc.', role:'Technical Architect – AWS DCV', loc:'remote', salary:'', clearance:'no', stage:3, notes:'Interview completed Jun 3. Recruiter: Hassan Waheed (hassan.waheed@onstak.com, 408-907-7467). Awaiting decision.', added:'2026-06-03', stageDate:'2026-06-03' },
  { id:'cybrexai-1', company:'Cybrex AI', role:'Cloud Security Specialist', loc:'remote', salary:'', clearance:'no', stage:2, notes:'Teams call Jun 3, 10:30am. Michael Gillespie (mgillespie@cybrexai.com). Awaiting follow-up.', added:'2026-06-03', stageDate:'2026-06-03' },
  { id:'dexian-1', company:'Dexian', role:'Solution Architect – Virginia', loc:'onsite', salary:'', clearance:'no', stage:2, notes:'Video interview Jun 15, 1pm. Saurabh Sharma (saurabh.sharma@dexian.com) & Abhay Kumar Sharma. Via HireLogic. Awaiting follow-up.', added:'2026-06-15', stageDate:'2026-06-15' },
  { id:'foreflight-1', company:'ForeFlight', role:'Principal Cloud Engineer – Infrastructure', loc:'remote', salary:'$208K–$244K', clearance:'no', stage:0, notes:'DR/BC & automation focus. Source: ZipRecruiter.', added:'2026-06-18', stageDate:'2026-06-18' },
  { id:'cts-1', company:'Compatible Technology Solutions', role:'Expert Cloud Engineer', loc:'onsite', salary:'$175K–$195K', clearance:'yes', stage:0, notes:'Springfield, VA. Requires active TS clearance.', added:'2026-06-18', stageDate:'2026-06-18' },
  { id:'globenet-1', company:'Globenet Consulting', role:'Solutions Architect – Amazon Connect', loc:'remote', salary:'$140K–$200K', clearance:'no', stage:0, notes:'Source: ZipRecruiter.', added:'2026-06-18', stageDate:'2026-06-18' },
  { id:'relevancelab-1', company:'Relevance Lab', role:'Lead Solutions Architect – AWS Cloud Developer', loc:'remote', salary:'DOE', clearance:'no', stage:0, notes:'Healthcare platform. Source: Dice.', added:'2026-06-18', stageDate:'2026-06-18' },
  { id:'barnumfg-1', company:'Barnum FG', role:'Solution Architect – Virginia', loc:'onsite', salary:'', clearance:'no', stage:2, notes:'Video discussion with Quincy West (qwest@barnumfg.com). Virginia-based role.', added:'2026-06-19', stageDate:'2026-06-19' },
  { id:'igniteis-1', company:'Ignite IT Services', role:'Senior Cloud Engineer', loc:'remote', salary:'', clearance:'no', stage:2, notes:'Recruiter: Royce Kim (rkim@igniteitservices.com).', added:'2026-06-19', stageDate:'2026-06-19' },
  { id:'akima-1', company:'Akima', role:'Senior Cloud Security Architect', loc:'remote', salary:'$220K–$235K', clearance:'yes', stage:1, notes:'Applied Jun 8.', added:'2026-06-08', stageDate:'2026-06-08' },
  { id:'baesystems-1', company:'BAE Systems', role:'Expert Solutions Architect – Cloud', loc:'remote', salary:'$147K–$249K', clearance:'yes', stage:1, notes:'Applied Jun 8.', added:'2026-06-08', stageDate:'2026-06-08' },
  { id:'accenturefed-1', company:'Accenture Federal', role:'Cloud Architect / Technical Lead', loc:'remote', salary:'$130K–$265K', clearance:'no', stage:1, notes:'Applied Jun 8.', added:'2026-06-08', stageDate:'2026-06-08' },
  { id:'caci-1', company:'CACI', role:'Cloud Solution Technical Lead', loc:'remote', salary:'$131K–$290K', clearance:'yes', stage:1, notes:'Applied Jun 8.', added:'2026-06-08', stageDate:'2026-06-08' },
  { id:'randstad-1', company:'Randstad Digital', role:'AWS Cloud Solutions Architect', loc:'remote', salary:'$190K–$215K', clearance:'no', stage:1, notes:'Applied Jun 8.', added:'2026-06-08', stageDate:'2026-06-08' },
  { id:'boozallen-1', company:'Booz Allen Hamilton', role:'Cloud Security Architect Lead', loc:'remote', salary:'$99K–$225K', clearance:'yes', stage:1, notes:'Applied Jun 8.', added:'2026-06-08', stageDate:'2026-06-08' },
  { id:'americansys-1', company:'American Systems Corp', role:'Senior Security Cloud Architect', loc:'remote', salary:'$159K–$266K', clearance:'yes', stage:1, notes:'Applied Jun 8.', added:'2026-06-08', stageDate:'2026-06-08' },
  { id:'metrostar-1', company:'Metrostar Systems', role:'Sr. Cloud Architect III', loc:'remote', salary:'$174K–$220K', clearance:'no', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'microsoft-1', company:'Microsoft', role:'Sr. Cloud Solution Architect – Federal AI', loc:'remote', salary:'$143K–$196K', clearance:'no', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'gdit-1', company:'GDIT', role:'Cloud Architect / Developer SME', loc:'remote', salary:'$187K–$230K', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'peraton-1', company:'Peraton', role:'Cloud Cybersecurity Architect', loc:'remote', salary:'$146K–$234K', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'synertex-1', company:'Synertex', role:'Cloud Architect w/ Clearance', loc:'remote', salary:'$139K–$177K', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'gama1-1', company:'GAMA-1 Technologies', role:'Sr. Cloud Security Architect', loc:'remote', salary:'$148K–$196K', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'alphao-1', company:'Alpha Omega Integration', role:'Senior Cloud Architect', loc:'remote', salary:'$180K+', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'basecamp-1', company:'Basecamp Consulting', role:'Enterprise Architect', loc:'remote', salary:'$150K–$180K', clearance:'no', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'eliassen-1', company:'Eliassen Group', role:'AWS Cloud Architect', loc:'remote', salary:'Contract – DOE', clearance:'no', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'omnifed-1', company:'Omni Federal', role:'Senior Cloud Engineer', loc:'remote', salary:'$192K–$220K', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'leidos-1', company:'Leidos', role:'Chief Systems Architect', loc:'remote', salary:'$154K–$278K', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'ecs-1', company:'ECS', role:'AWS/Microsoft Enterprise Cloud Architect SME', loc:'remote', salary:'$138K–$176K', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'unitedair-1', company:'United Airlines', role:'Cloud Network Security Architect', loc:'hybrid', salary:'$94K–$215K', clearance:'no', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'systemone-1', company:'System One', role:'Sr. Cloud Administrator – AWS GovCloud', loc:'remote', salary:'Contract – DOE', clearance:'yes', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'skyline-1', company:'Skyline Scientific', role:'Senior/Principal Software Architect', loc:'remote', salary:'$150K–$225K', clearance:'no', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'xcelhr-1', company:'XcelHR', role:'Cloud Solutions Architect', loc:'remote', salary:'$170K–$220K', clearance:'no', stage:1, notes:'Applied Jun 9.', added:'2026-06-09', stageDate:'2026-06-09' },
  { id:'effectual-1', company:'Effectual', role:'Cloud Architect', loc:'remote', salary:'$190K (submitted)', clearance:'no', stage:2, notes:'Recruiter: Patrick Wallace · pwallace@oxenhamgroup.com · (262) 294-4360 · Oxenham Group. Submitted at $190K — awaiting client response.', added:'2026-06-19', stageDate:'2026-06-19' },
  { id:'ignite-1', company:'Ignite IT', role:'Sr. Cloud Engineer', loc:'remote', salary:'TBD', clearance:'likely', stage:3, notes:'Interview TODAY at noon. Federal GovCon — clients include HHS, DHS/CBP, DISA, DoD, Army. Coral Springs FL / Ashburn VA. Ho Nguyen = Principal Cloud Architect (likely hiring team). Confirm clearance req.', added:'2026-06-25', stageDate:'2026-06-25' },
  { id:'amazon-govsa-1', company:'Amazon (AWS)', role:'Sr. Security Solutions Architect – Global Government', loc:'hybrid', salary:'$149K–$196K', clearance:'likely', stage:0, notes:'AWS federal SA role — GovCloud, Arlington VA, remote optional. Perfect profile match. Posted 5 days ago.', added:'2026-06-27', stageDate:'2026-06-27' },
  { id:'presidio-1', company:'Presidio', role:'Principal Architect', loc:'remote', salary:'$148K–$199K', clearance:'no', stage:0, notes:'Major multi-cloud IT solutions provider. Remote. Posted 1 day ago.', added:'2026-06-27', stageDate:'2026-06-27' },
  { id:'datawiz-1', company:'Datawiz', role:'Microsoft Cloud Engineer, Senior', loc:'hybrid', salary:'$170K–$200K', clearance:'likely', stage:0, notes:'Azure/Microsoft cloud engineering, Chantilly VA (federal area), hybrid remote. Strong salary ceiling. Posted 1 day ago.', added:'2026-06-27', stageDate:'2026-06-27' },
];

const STAR_STORIES = {
  mgn_migration: { lp:'Ownership', title:'1,000+ Server AWS MGN Migration', s:'Fannie Mae’s legacy on-premises data center was reaching end-of-life, housing 1,000+ Windows and Linux servers supporting $4T in mortgage assets. The business required a migration to AWS without disrupting 24/7 financial operations or regulatory reporting.', t:'As Principal Cloud Architect, I owned the full migration program end-to-end — architecture, tooling, wave planning, cutover execution, and rollback — with zero tolerance for unplanned downtime.', a:'Designed a factory migration model using AWS MGN (Application Migration Service). Built dependency maps to group servers into 20+ waves ordered by risk. Created automated post-migration validation scripts and rollback runbooks with sub-30-minute RTO. Trained a team of 8 engineers on MGN tooling. Ran full dry-run cutovers for every wave before production execution.', r:'Migrated 1,000+ servers with zero unplanned outages. Program completed on schedule and ~15% under budget. Decommissioning the legacy data center eliminated millions in annual infrastructure costs and removed a major operational risk.' },
  finops: { lp:'Invent & Simplify', title:'25% Cloud Cost Reduction via FinOps', s:'Post-migration, Fannie Mae’s AWS spend was growing 12% month-over-month with no attribution across business units. Engineering teams had no visibility into what they were spending or why.', t:'Build a FinOps practice from scratch and reduce cloud waste without impacting application performance or delivery velocity.', a:'Implemented a tagging taxonomy across all AWS accounts for per-team cost attribution. Built CloudWatch + Cost Explorer dashboards visible to each business unit. Identified idle EC2 instances, over-provisioned RDS clusters, and orphaned EBS volumes. Negotiated a 3-year EC2 Savings Plan. Added auto-scaling policies to 40+ workloads. Ran monthly FinOps reviews with engineering leads.', r:'Reduced total cloud spend ~25% within 8 months while workload count grew 30%. The governance model became the standard for all new workload onboarding across the organization.' },
  vmware_sddc: { lp:'Deliver Results', title:'10+ VMware Cloud on AWS SDDCs Delivered', s:'Fannie Mae’s core applications were tightly coupled to VMware vSphere on-premises. A full rewrite or lift-and-shift was a multi-year effort; the business needed a hybrid cloud bridge that let teams migrate at their own pace without application changes.', t:'Architect and deliver a VMware Cloud on AWS (VMC) footprint to enable phased hybrid migration with minimal operational disruption.', a:'Designed multi-SDDC architecture across two AWS regions. Configured NSX-T for east-west microsegmentation, deployed HCX for live workload migration (vMotion over Direct Connect), and implemented VMware SRM for automated DR failover. Built SDDC operational runbooks and engineering training materials.', r:'Delivered 10+ VMware Cloud SDDCs. Enabled 200+ VMs to live-migrate from on-prem with zero downtime via HCX vMotion. Cut DR failover time from 4 hours to under 45 minutes using SRM automation.' },
  zero_trust: { lp:'Dive Deep', title:'Zero Trust Architecture — NIST 800-53 Compliance', s:'Post-migration, Fannie Mae’s security posture relied on perimeter-based controls that didn’t translate to cloud. The CISO required a Zero Trust model to meet NIST 800-53, SOX audit requirements, and evolving regulatory expectations.', t:'Lead Zero Trust architecture design and implementation across the entire AWS estate without disrupting production workloads.', a:'Implemented Illumio Zero Trust Segmentation for east-west traffic visibility and policy enforcement. Designed NSX-T microsegmentation rules. Rebuilt network security as Terraform code — deny-by-default NACLs and security groups with application-specific allow lists. Built real-time traffic flow maps to detect anomalous communication patterns.', r:'Passed NIST 800-53 security assessment with zero critical findings. Reduced the blast radius of any single workload compromise to fewer than 5 servers. Deployed across all production workloads within 6 months with zero production incidents during rollout.' },
  earn_trust: { lp:'Earn Trust', title:'High-Risk Migration — CIO Approval & Flawless Execution', s:'A critical Fannie Mae batch processing system — responsible for overnight mortgage settlement reports to FHFA — required migration during a narrow regulatory reporting window. Any failure would delay settlement reports, triggering regulatory scrutiny and potential financial penalties.', t:'Build the risk case, get CIO/CISO sign-off, and execute a flawless cutover in a 4-hour window with no margin for error.', a:'Built a comprehensive risk mitigation playbook with sub-30-minute RTO rollback procedures. Conducted two full dry-run migrations with all stakeholders observing. Presented a one-page risk/benefit framework to the CIO with quantified go/no-go criteria. On migration night, ran a live war room with real-time dashboards visible to all senior stakeholders throughout the window.', r:'Migration completed in the 4-hour window with zero issues. FHFA reports delivered on time with no regulatory escalation. CIO cited the program as the new model for all high-risk changes and invited me to present the methodology to the technology risk committee.' },
  proposals: { lp:'Customer Obsession', title:'$90M+ in Federal Technical Proposals', s:'My company needed to win competitive government IT contracts in a market dominated by established primes. Our technical differentiation had to be clear and credible to source selection evaluators with strict scoring criteria.', t:'Lead technical approach writing and cloud architecture design for major federal RFP responses across multiple solicitations.', a:'Developed technical approach narratives, cloud reference architectures, staffing plans, and past performance write-ups. Collaborated with BD, contracts, and pricing teams to ensure technical-price alignment. Ran internal red teams against competing approaches to sharpen differentiators. Built reusable architecture diagram libraries and proposal templates.', r:'Contributed to $90M+ in proposal submissions. Technical approaches I developed became reusable templates, accelerating future responses by ~30% and improving consistency across the organization’s proposal practice.' },
};

const PREP_DATA = {
  covalent: { company:'Covalent Solutions', role:'Principal Enterprise Infrastructure Architect', when:'Jun 18 · 9:00 AM ET · Google Meet', contact:'Thi Pham · thi.pham@covalentsolutions.com', salary:'$175K–$195K · Target: $195K firm or walk', about:'Covalent Solutions is a government-focused IT consulting and data analytics firm serving federal agencies in the DC/Virginia market. They specialize in legacy system modernization, cloud migration, and enterprise IT infrastructure — heavily AWS-aligned. They are actively hiring for infrastructure leaders to lead cloud transformation engagements.', keywords:['Cloud Infrastructure','Legacy Modernization','AWS','FedRAMP','Enterprise Architecture','Government IT'], talking_points:['Lead with Fannie Mae scale: cloud infrastructure at a $4T regulated financial institution — 1,000+ servers to AWS via MGN, 10+ VMware Cloud SDDCs, ~25% FinOps reduction.','Architecture depth: enterprise-scale AWS — VPC design, Transit Gateways, multi-account strategies, landing zones.','Government background: DoS, DoJ, DISA, OPM — mention FedRAMP, NIST 800-53, Zero Trust directly.','TS clearance eligible for immediate reinstatement — major differentiator for gov contractors.','VMware on AWS: 10+ SDDCs delivered — relevant for VMC migrations for agency clients.'], questions:['What government agencies or contracts does this role primarily support?','What does the typical engagement look like — embedded at a client site, or based out of your office?','What cloud platforms are your agency clients currently running on vs. migrating to?','What does the team structure look like — how many architects, and how is work distributed?','What does success look like in the first 90 days?'], watch_for:'Low salary ceiling — $195K should be the floor for this level of experience. Confirm W2 vs. C2C. Ask about clearance sponsorship timeline if active TS is needed.' },
  mission_bridge: { company:'Mission Bridge Partners', role:'Senior Solutions Architect (HHS)', when:'Jun 18 · 2:00 PM ET · Microsoft Teams', contact:'Evan McIntosh · evan@missionbridgepartners.com', salary:'Salary not disclosed — target $180K+ W2 or $90/hr C2C', about:'Mission Bridge Partners is a government IT staffing and solutions firm placing technical talent on federal contracts. This role supports HHS — actively modernizing cloud infrastructure, data analytics, and IT service delivery. The HHS OCIO is driving major AWS cloud adoption across its operating divisions.', keywords:['HHS','Federal Cloud','FedRAMP','NIST 800-53','AWS GovCloud','Healthcare IT','Government Contracting'], talking_points:['Federal agency pedigree: supported DoS, DoJ, DISA, OPM — comparable or more stringent than HHS.','Clearance advantage: TS clearance eligible for immediate reinstatement.','AWS GovCloud + FedRAMP: direct experience with FedRAMP-authorized workloads, NIST 800-53, ATO processes.','Proposal writing: $90M+ in technical proposals — HHS contracts are large multi-year IDIQs.','Scale + rigor: regulated financial data is analogous to sensitive health data — same access controls, audit trails, zero-trust.'], questions:['Is this role on an existing HHS contract or a new pursuit?','What is the contract vehicle — SEWP, CIO-SP3, agency-specific IDIQ?','What is the clearance requirement — Public Trust, Secret, or TS?','Is this a W2 or C2C/1099 engagement? What is the bill rate range?','What is the expected period of performance?','Is there flexibility for remote work or primarily on-site at HHS facilities?'], watch_for:'Confirm the compensation model upfront — staffing firms sometimes present W2 hourly rates that look like salary. Ask: "Is this W2 hourly, W2 salaried, or C2C?" Target $90/hr+ C2C or $180K W2.' },
  four_points: { company:'Four Points Technology', role:'Sr. Solutions Architect', when:'Mon Jun 22 · 10:00 AM ET · Microsoft Teams', contact:'Lori Constantino (lconstantino@4points.com) · Erik Korondy · Joel Lipkin · Dana Bean · Denise Harrison (CIO)', salary:'Not disclosed — target $195K–$210K or senior band', about:'Four Points Technology is an SDVOSB delivering IT solutions to the federal government since 2002 (Chantilly, VA; ~$63.5M revenue). They won the AWS Public Sector Solution Provider Partner of the Year (2025) — a serious AWS partner. Vehicles include GSA Schedule 70, SEWP V, and agency IDIQs. Denise Harrison (CIO) is a former GTSI connection.', keywords:['SDVOSB','AWS Partner','Federal IT','GovCloud','FedRAMP','SEWP V','GSA Schedule 70','DoD','Cloud Advisory'], talking_points:['RECONNECT with Denise: acknowledge the GTSI connection and build personal rapport.','AWS Partner of the Year angle: align with their 2025 award; you hold the Solutions Architect cert.','Federal contract DNA: DoS, DoJ, DISA, OPM — you speak federal IT; mention GSA Schedule experience.','TS clearance: lead with TS eligibility for SDVOSB fed work.','Scale wins: 1,000+ server MGN migration, 10+ VMware SDDCs, $90M in proposals.','Cloud Advisory: emphasize FinOps (25% reduction) and architecture reviews.'], questions:['What federal agencies does this Solutions Architect role primarily support?','Is this a billable client-facing role or an internal practice-building role?','What is driving the AWS Partner of the Year growth and how does this role fit?','What clearance level does this position require?','What does the compensation structure look like — base + bonus, or fully loaded?','What is the onboarding timeline?'], watch_for:'Panel interview with 5 people (Lori, Denise, Erik, Joel, Dana) — prepare for multiple stakeholders; address each by name; this is a serious evaluation.' },
  amazon_recruiter: { company:'Amazon (AWS)', role:'WWPS Partners SA — Recruiter Screen', when:'Mon Jun 22 · 2:00–2:30 PM ET · Phone: +1 (202) 531-9876', contact:'shaunnav@amazon.com', salary:'Target: $220K–$250K TC (base + RSUs + bonus). Do NOT anchor low.', about:'Amazon WWPS Partners SA works with AWS’s ecosystem of government-focused systems integrators and consulting partners (Booz Allen, SAIC, Leidos, Deloitte, Accenture Federal). Partner-facing: help partners build AWS competency, run architecture reviews, support proposals, run workshops. This recruiter screen gates the technical loop (Andy Banks, Jun 24).', keywords:['WWPS','Public Sector','Partner SA','AWS GovCloud','FedRAMP','Architecture','Partner Enablement'], talking_points:['This is a fit/logistics call — be concise; save deep technical for Andy Banks.','30-second hook: 25 years enterprise IT; current Principal at Fannie Mae; AWS migrations at scale; AWS SA cert; TS reinstatement-eligible; DoS/DoJ/DISA/OPM experience.','Salary — be bold: state $220K–$250K total comp; confirm RSU/equity; don’t say "whatever is fair".','Availability: be clear on notice period and start-date flexibility.','Clearance: held TS for X years; reinstatement typically 30–90 days.'], questions:['Can you walk me through the interview process from here?','What does the WWPS Partners SA team look like — size, geography, structure?','Is this primarily defense/intel partners, civilian agency partners, or a mix?','What is the base + RSU + bonus structure for this level?','What is the target start date?'], watch_for:'The recruiter may ask current salary — you are not required to disclose. Say: "I’m targeting $220K–$250K total comp based on market and experience." Hold firm.' },
  hampton_north: { company:'Hampton North (recruiter for undisclosed client)', role:'Technical Lead, Platform & Cyber Resilience', when:'Tue Jun 23 · 1:20–1:40 PM ET · Phone: (323) 989-1650', contact:'Ruby Murphy · ruby.murphy@hamptonnorth.com', salary:'Unknown — ask early. Target $180K+ or $90/hr C2C', about:'Hampton North is a premium cybersecurity-specialist recruiting firm. Ruby Murphy is placing a "Technical Lead, Platform & Cyber Resilience" role — likely a financial services firm, tech company, or large enterprise. This is a recruiter discovery call.', keywords:['Cyber Resilience','Zero Trust','Platform Engineering','NSX-T','Cloud Security','Technical Lead'], talking_points:['This is a recruiter call — be memorable; give clear soundbites she can pitch to her client.','Cyber resilience angle: Zero Trust, NSX-T/V segmentation, NACL design, DR (VMware SRM, AWS DR).','Platform leadership: enterprise platform teams at Fannie Mae scale, cross-team technical leadership.','Security posture: FedRAMP, NIST 800-53, Illumio Zero Trust, network segmentation.','Ask about the end client early: "Can you share who the client is, or at least the sector?"'], questions:['Who is the end client — can you share the company name?','What industry/sector is the client in?','Is this a leadership role with direct reports, or an IC technical lead?','What does "Platform & Cyber Resilience" mean specifically in their context?','What is the compensation range the client has approved?','Is this a permanent role, contract, or contract-to-hire?'], watch_for:'Hampton North is cybersecurity-specialist — if the role skews pen-test/red team, that’s not your core. Confirm the role is cloud/platform/architecture-focused.' },
  amazon_interview: { company:'Amazon (AWS)', role:'Senior Solutions Architect — WWPS Partners SA (Technical Interview)', when:'Wed Jun 24 · 10:30–11:30 AM ET · Zoom 92792832434 / PW 13048620', contact:'Andy Banks · shaunnav@amazon.com (coordinator)', salary:'Already discussed with recruiter — hold your number: $220K–$250K TC', about:'AWS WWPS Partners SA supports government-focused SIs and consulting partners. The SA helps partners build AWS competency, participates in architecture reviews, supports proposals, runs enablement. Expect behavioral questions on Amazon Leadership Principles + 1–2 architecture scenarios. Andy Banks is likely a senior SA or bar raiser.', keywords:['Leadership Principles','WWPS','Partner Enablement','AWS GovCloud','FedRAMP','Architecture','Technical Depth'], talking_points:['Leadership Principles — all 6 STAR stories map to LPs. Practice crisp STAR (S→T→A→R with metrics).','Architecture scenario: migrate a classified workload to AWS GovCloud — landing zone, Organizations, SCPs, FedRAMP boundary, encryption, audit (CloudTrail/Config), segmentation (TGW/NACLs/SGs), DR.','Partner SA angle: enable partners — workshops, reference architectures, help win RFPs.','Earn Trust: communicate risk to senior stakeholders — lead with the high-risk migration story.','Zoom test: check audio/video the night before. ID 92792832434, PW 13048620.'], questions:['What does the partner portfolio look like for this territory?','How does WWPS Partners SA interface with the direct field SA org?','What is the biggest technical challenge partners face in the public sector right now?','What does ramp-up look like — time to full productivity?','What does career growth look like within WWPS SA?'], watch_for:'Amazon interviews are heavily LP-based. Every answer needs crisp STAR structure. Aim for 2–3 minutes per story.' },
  effectual: { company:'Effectual', role:'Cloud Architect', when:'TBD — submitted at $190K, awaiting client response', contact:'Patrick Wallace · pwallace@oxenhamgroup.com · (262) 294-4360 · Oxenham Group', salary:'$190K submitted — push for $195K–$200K if there is room.', about:'Effectual (effectual.ai) is an AWS-focused cloud professional services firm. The Cloud Architect owns technical leadership of client engagements end-to-end — landing zones, EKS/ECS, S3, Transit Gateway, EC2 environments — and participates in pre-sales. An IC role at a senior technical level.', keywords:['AWS','Professional Services','Cloud Architecture','EKS','ECS','Control Tower','Terraform','IaC','DevOps','FinOps','Pre-Sales'], talking_points:['Technical ownership at scale: full cloud architecture for a $4T regulated environment — 1,000+ servers via MGN, 10+ VMware SDDCs, 25% FinOps.','IaC depth (required): Terraform and CloudFormation are explicitly required — lead with IaC.','Client-facing credibility: translate complex AWS architecture into business narratives; run design reviews.','Pre-sales angle: $90M+ in federal proposals shows you can articulate value to prospects.','Container & DevOps: EKS/ECS, GitHub/GitLab pipelines, CI/CD.'], questions:['What types of clients does this role support — commercial, federal, or a mix?','How many engagements would a Cloud Architect carry in parallel?','What does pre-sales involvement look like in practice?','What does the team structure look like — architects to engagement managers?','Is there a path to a practice lead role over time?','What does compensation look like beyond base?','What is the expected start timeline?'], watch_for:'Confirm W2 vs. C2C and travel expectations — "professional services" often means client-site visits. Push toward $195K–$200K. Clarify remote vs hybrid.' },
  ignite_it: { company:'Ignite IT', role:'Sr. Cloud Engineer', when:'TODAY — noon interview', contact:'igniteitservices.com · info@igniteitservices.com · Coral Springs FL / Ashburn VA', salary:'TBD — market for Sr. Cloud Engineer at GovCon is $130K–$175K; push toward the top.', about:'Ignite IT is a federal GovCon IT firm (~100+ engineers, $2B+ won contract value, Inc 5000). Clients: HHS, DHS/CBP, DoS, DISA, U.S. Army. DevSecOps-first, ISO 27001, CMMI-SVC/3. Principal Cloud Architect: Ho Nguyen. CDO: Aaron Hopp. Cloud is almost certainly AWS GovCloud; FedRAMP and RMF front-and-center. Notable win: DHS/CBP modernization — 100% more functionality, 50% cost reduction in 6 months.', keywords:['AWS GovCloud','FedRAMP','RMF','DevSecOps','Cloud Migration','IT Modernization','CI/CD','Terraform','IaC','Federal','Agile','CMMI','ISO 27001','Security Clearance','Hyper Automation'], talking_points:['Federal-grade rigor maps directly: $4T regulated environment with strict compliance, audit trails, security controls.','Migration scale (CBP parallel): MGN migration of 1,000+ servers = same ROI discipline as their CBP win.','DevSecOps is their DNA: automated security testing in CI/CD, IaC (Terraform/CloudFormation), shift-left.','IT Modernization / Ignite AIL (Assess→Identify→Leverage): mirror their methodology language.','Mission alignment: open and close with mission language — programs that matter.','Cost optimization / FinOps: 25% infra cost reduction at Fannie Mae as a proof point.'], questions:['What agencies and programs would this role primarily support?','Does this position require an active security clearance — and at what level?','What cloud platforms are in use — AWS GovCloud, Azure Government, or a mix?','How does this role interface with Ho Nguyen (Principal Cloud Architect)?','What does the DevSecOps pipeline look like on active programs?','Is this fully remote, or is proximity to Coral Springs or Ashburn expected?','What does growth look like — path to Lead or Principal Architect?','What is the compensation structure — base, bonus, clearance premium, cert reimbursement?'], watch_for:'Clearance is the #1 unknown — DHS/CBP and Army programs may require Public Trust, Secret, or TS. Ask directly. Clarify W2 vs C2C, remote vs hybrid, geographic requirements. CMMI firm — respect structured, methodology-driven answers.' },
};

// ─── transform to app.html schema ───────────────────────────────────────────
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const stars = Object.entries(STAR_STORIES).map(([k, v]) => ({ id: 'star-' + k, lp: v.lp, title: v.title, s: v.s, t: v.t, a: v.a, r: v.r }));
const prep = Object.entries(PREP_DATA).map(([k, p]) => ({
  id: 'prep-' + k,
  company: p.company, role: p.role, when: p.when, contact: p.contact, salary: p.salary,
  about: p.about, points: p.talking_points, questions: p.questions, keywords: p.keywords, watch: p.watch_for,
}));

const seed = { pipeline: ADDITIONS, prep, stars };
const out = '/* Created by GuntherCloudSolutions — seed data ported from the pinned Job Search Dashboard. */\n'
  + 'window.CTO_SEED = ' + JSON.stringify(seed, null, 1) + ';\n';

const here = dirname(fileURLToPath(import.meta.url));
const dest = join(here, '..', '..', 'seed-data.js');
writeFileSync(dest, out);
console.log('Wrote', dest, '— pipeline:', seed.pipeline.length, 'prep:', seed.prep.length, 'stars:', seed.stars.length);
